### ISSUE TITLE
Some intermediate files seem missing

### ISSUE THREAD

**Issue by realliyifei** [nd-hal/fair-psych-nlp#1]
for example

<img width="1321" alt="image" src="https://github.com/nd-hal/fair-psych-nlp/assets/32441766/3270e675-d4c7-4f59-9ef8-81dd2452d5a6">

**Comment by jplalor** [comment]
Thanks for pointing this out! I'm looking into it and hope to have an update in the next few days.

**Comment by jplalor** [comment]
I think this issue is more related to the naacl-2022 project. I created a PR there that I plan on merging later today: https://github.com/nd-hal/naacl-2022/pull/1 

I added a new file to the plotting_data folder that can be used with the generate_plots.R file to generate the plots and tables from the paper. 
The Jupyter notebook is more for demonstration, if you have your own model outputs and want to calculate performance and fairness (it's still quite messy :)  )

**Comment by realliyifei** [comment]
I see. Thank you John!
